USE chatbot_db;

CREATE TABLE CONVERSATION (
    CONVERSATION_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL DEFAULT 'New Conversation',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CONVERSATION_ID)
) ENGINE=InnoDB;

CREATE TABLE CHAT_HISTORY (
    HISTORY_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    CONVERSATION_ID BIGINT(20) NOT NULL,
    QUESTION TEXT NOT NULL,
    ANSWER TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (HISTORY_ID),
    FOREIGN KEY (CONVERSATION_ID) REFERENCES CONVERSATION (CONVERSATION_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 예시 데이터 삽입 (주석 해제 시 사용)
-- INSERT INTO CONVERSATION (TITLE) VALUES ('Copilot 스타일 챗봇 대화 1');
-- INSERT INTO CHAT_HISTORY (CONVERSATION_ID, QUESTION, ANSWER) 
-- VALUES (1, 'RAG가 뭐야?', 'RAG는 Retrieval-Augmented Generation의 약자로...'),
--        (1, 'Vector DB 추천해줘.', 'FAISS, Qdrant, Milvus 등이 있습니다.');
